language: go

go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4

before_install:
  - git clone https://github.com/Softmotions/ejdb.git
  - cd ejdb
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - make
  - cd ../..
