language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4

before_install:
  - git clone https://github.com/Softmotions/ejdb.git
  - cd ejdb
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - make
  - cd ../..
  - export LIBRARY_PATH=$LIBRARY_PATH:$(pwd)/ejdb/build/src
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/ejdb/build/src
  - export CPATH=$CPATH:$(pwd)/ejdb/src:$(pwd)/ejdb/src/bson:$(pwd)/ejdb/build/src/generated:$(pwd)/ejdb/src/tcutil
